# Generated by Django 3.0.6 on 2020-06-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='guest',
            name='user_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
