# Generated by Django 3.0.6 on 2020-06-29 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20200629_2120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
